// This file was autogenerated using this Sequelize CLI command
//
// $ sequelize model:create --name Manager --attributes 
//    "fullName:string, storeZip:string, uniformColor:string, uniformNumber:string" 

'use strict';

// export model to index.js
module.exports = function(sequelize, DataTypes) {
  // it's Manager, so named
  var Manager = sequelize.define('Manager', {
    // a fullName string
    fullName: DataTypes.STRING,
    // a StoreZip string
    // (note: saving this as int would delete any leading 0)
    // (i.e. 07740 becomes 7748)
    storeZip: DataTypes.STRING,
    // uniformColor as String
    uniformColor: DataTypes.STRING,
    // uniformNumber as String
    uniformNumber: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        // associations can be defined here
        // THIS IS WHERE THE MAGIC HAPPENS
      }
    }
  });
  // return it, and effectively export it
  return Manager;
};